### ISSUE TITLE
Question: Mojang account authentication

### ISSUE THREAD

**Issue by HarryPuttar5832** [appenz/minebot#3]
Is there a way we can add like Cracked or offline Accounts with the code?

and which file do i need to start with? am pretty much newbie in selecting files...

**Comment by INotSleep** [comment]
Cracked: 
Comment the password field and in username field paste your nickname
Premium:
Fill all fields.

**Comment by appenz** [comment]
Not planning to support cracked accounts or offline servers. Minecraft isn't that expensive, I think it's only fair to pay for it.
