### ISSUE TITLE
Mineflayer

### ISSUE THREAD

**Issue by INotSleep** [appenz/minebot#4]
Make your own package. Minecraft multiplayer based on socket. You can get socket packets in mineflayer code. Now it lookl ike shitcode. Im not learned python, but code very scared me.

**Comment by appenz** [comment]
I am dependent on Mineflayer and it's way too large to easily replace it. I not only rely on Prismarine's protocol libraries but also on some of their pathfinding. And using it via the Python bridge obviously doesn't help. 

Sorry, but closing with WONTFIX.
