### ISSUE TITLE
Possible bugs? (and a recommendation) 

### ISSUE THREAD

**Issue by Sedrowow** [appenz/minebot#5]
I think there might be sone bugs to check out.  If i run a command (ot push the button) like "chop tree"or mine ####, (at almost every chest required task) sometimes there is in the command line a chest open timeout.
Also i recognized he gets very often stuck on doing tasks (like at chop trees he gets stuck  at searching trees) (or he gets stuck after restocking (in the GUI there stays the restocking task, and the bit does nothing))

I play on 1.16.5

I have also a recommendation. Try to add to account-sample.py a server port option.
And in pybot.py the following line of code to createbot:
'port' : self.account['port'],

Because i got a server that does nit have the standard port (i checked this and it worked fine for me.

**Comment by Sedrowow** [comment]
Ok i double checked the mentioned bugs, the "open container' timeout only happens if i stand near the bot (i saw he tried to access my inventory what of course is not possible.)

About the stuck on task: it appears to happen randomly, after some attempts to get it working.

**Comment by appenz** [comment]
I am aware of the container timeout issue and I believe it is a bug in the underlying python bindings for the Prismarine protocol library. I looked at it in some depth and wasn't able to fix it at the python layer. The best I can do is try to catch them, but at some point it breaks. For me they happened seldom enough (less than once every 2 hours) that it wasn't an issue.

I have never seen it gettin stuck permanently. Searching for a tree if there isn't one can take a long time though.

Server port is a good suggestion. I'll add a PR for that.
