### ISSUE TITLE
Support Cracked Accounts

### ISSUE THREAD

**Issue by Banana1059** [appenz/minebot#8]
Is it possible to support logging in to cracked accounts instead of just Mojang accounts? Also, could you also try to make it where you can run more then one bot at once without them interfering with each other

**Comment by TrxppyDrkp** [comment]
buy java

**Comment by ajh123** [comment]
yes, just use an empty password.

**Comment by appenz** [comment]
Sorry, but I have zero interest in supporting cracked accounts.
